name: Test OpenOCD

on:
  workflow_call: {}
  workflow_dispatch: {}
jobs:
  run-macos-x86-host:
    name: Test OpenOCD on MacOS-x86
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download files / artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: openocd-macos-x86
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run and check OpenOCD
        run: chmod +x bin/openocd && python tools/test_openocd.py bin/openocd

  run-macos-arm64-host:
    name: Test OpenOCD on MacOS-arm64
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download files / artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: openocd-macos-arm64
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run and check OpenOCD
        run: chmod +x bin/openocd && python tools/test_openocd.py bin/openocd

  run-linux-host:
    name: Test OpenOCD on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download files / artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: openocd-linux
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run and check OpenOCD
        run: chmod +x bin/openocd && python tools/test_openocd.py bin/openocd

  run-win-host:
    name: Test OpenOCD on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download files / artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: openocd-windows
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run and check OpenOCD
        run: python tools/test_openocd.py bin\openocd
